/**
 * Very basic Markdown to LaTeX converter using string replacement.
 * Handles headings, bold, italic, code blocks, and basic lists.
 */
export function markdownToLatex(markdown: string): string {
    let latex = "% Generated by MD-Lite\n\\documentclass{article}\n\\usepackage[utf8]{inputenc}\n\\usepackage{hyperref}\n\\begin{document}\n\n";

    const lines = markdown.split("\n");
    let inCodeBlock = false;
    let inList = false;

    for (let i = 0; i < lines.length; i++) {
        let line = lines[i];

        // Code block toggle
        if (line.trim().startsWith("```")) {
            inCodeBlock = !inCodeBlock;
            if (inCodeBlock) {
                latex += "\\begin{verbatim}\n";
            } else {
                latex += "\\end{verbatim}\n";
            }
            continue;
        }

        if (inCodeBlock) {
            latex += line + "\n";
            continue;
        }

        if (!line.trim()) {
            if (inList) {
                latex += "\\end{itemize}\n\n";
                inList = false;
            } else {
                latex += "\n";
            }
            continue;
        }

        // Headings
        const headingMatch = line.match(/^(#{1,6})\s+(.*)/);
        if (headingMatch) {
            const level = headingMatch[1].length;
            const text = headingMatch[2];
            if (level === 1) latex += `\\section{${text}}\n`;
            else if (level === 2) latex += `\\subsection{${text}}\n`;
            else if (level === 3) latex += `\\subsubsection{${text}}\n`;
            else latex += `\\paragraph{${text}}\n`;
            continue;
        }

        // Lists
        const listMatch = line.match(/^[-*+]\s+(.*)/);
        if (listMatch) {
            if (!inList) {
                latex += "\\begin{itemize}\n";
                inList = true;
            }
            latex += `\\item ${listMatch[1]}\n`;
            continue;
        } else if (inList) {
            latex += "\\end{itemize}\n\n";
            inList = false;
        }

        // Inline formatting
        line = line.replace(/\*\*(.*?)\*\*/g, "\\textbf{$1}");
        line = line.replace(/__(.*?)__/g, "\\textbf{$1}");
        line = line.replace(/\*(.*?)\*/g, "\\textit{$1}");
        line = line.replace(/_(.*?)_/g, "\\textit{$1}");
        line = line.replace(/\[(.*?)\]\((.*?)\)/g, "\\href{$2}{$1}");

        latex += line + "\n";
    }

    if (inList) {
        latex += "\\end{itemize}\n";
    }

    latex += "\n\\end{document}\n";
    return latex;
}
